#export CLUSTER_NAME=tec-cp4aiops-3c14aa1ff2da1901bfc7ad8b495c85d9-0000.eu-de.containers.appdomain.cloud

# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# WEB
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","availableReplicas": 1,"createdReplicas": 1,"dataCenter": "demo","desiredReplicas": 1,"entityTypes": ["deployment"],"matchTokens": ["web-deployment"],"name": "web-deployment","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "web-deployment-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","dataCenter": "demo","entityTypes": ["pod"],"matchTokens": ["web-pod"],"name": "web-pod","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "web-pod-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","dataCenter": "demo","entityTypes": ["service"],"matchTokens": ["web-svc"],"name": "web-svc","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "web-svc-id"}'



curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "web-id","_toUniqueId": "web-pod-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "web-pod-id","_toUniqueId": "web-svc-id"}'


# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# SHIPPING
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","availableReplicas": 1,"createdReplicas": 1,"dataCenter": "demo","desiredReplicas": 1,"entityTypes": ["deployment"],"matchTokens": ["shipping"],"name": "shipping","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "shipping-deployment-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","dataCenter": "demo","entityTypes": ["pod"],"matchTokens": ["shipping-pod"],"name": "shipping-pod","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "shipping-pod-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","dataCenter": "demo","entityTypes": ["service"],"matchTokens": ["shipping-svc"],"name": "shipping-svc","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "shipping-svc-id"}'



curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "shipping-deployment-id","_toUniqueId": "shipping-pod-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "shipping-pod-id","_toUniqueId": "shipping-svc-id"}'


# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# CART
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","availableReplicas": 1,"createdReplicas": 1,"dataCenter": "demo","desiredReplicas": 1,"entityTypes": ["deployment"],"matchTokens": ["cart"],"name": "cart","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "cart-deployment-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","dataCenter": "demo","entityTypes": ["pod"],"matchTokens": ["cart-pod"],"name": "cart-pod","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "cart-pod-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","dataCenter": "demo","entityTypes": ["service"],"matchTokens": ["cart-svc"],"name": "cart-svc","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "cart-svc-id"}'


curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "cart-deployment-id","_toUniqueId": "cart-pod-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "cart-pod-id","_toUniqueId": "cart-svc-id"}'


# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#USER
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","availableReplicas": 1,"createdReplicas": 1,"dataCenter": "demo","desiredReplicas": 1,"entityTypes": ["deployment"],"matchTokens": ["user"],"name": "user","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "user-deployment-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","dataCenter": "demo","entityTypes": ["pod"],"matchTokens": ["user-pod"],"name": "user-pod","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "user-pod-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","dataCenter": "demo","entityTypes": ["service"],"matchTokens": ["user-svc"],"name": "user-svc","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "user-svc-id"}'



curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","availableReplicas": 1,"createdReplicas": 1,"dataCenter": "demo","desiredReplicas": 1,"entityTypes": ["volume"],"matchTokens": ["user-db"],"name": "user-db","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "user-db-id"}'



curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "user-deployment-id","_toUniqueId": "user-pod-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "user-pod-id","_toUniqueId": "user-svc-id"}'

curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "user-deployment-id","_toUniqueId": "user-db-id"}'

curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "runsOn","_fromUniqueId": "user-db-id","_toUniqueId": "mongodb-id"}'


# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#CATALOGUE
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","availableReplicas": 1,"createdReplicas": 1,"dataCenter": "demo","desiredReplicas": 1,"entityTypes": ["deployment"],"matchTokens": ["catalogue"],"name": "catalogue","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "catalogue-deployment-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","dataCenter": "demo","entityTypes": ["pod"],"matchTokens": ["catalogue-pod"],"name": "catalogue-pod","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "catalogue-pod-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","dataCenter": "demo","entityTypes": ["service"],"matchTokens": ["catalogue-svc"],"name": "catalogue-svc","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "catalogue-svc-id"}'



curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","availableReplicas": 1,"createdReplicas": 1,"dataCenter": "demo","desiredReplicas": 1,"entityTypes": ["volume"],"matchTokens": ["catalogue-db"],"name": "catalogue-db","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "catalogue-db-id"}'



curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "catalogue-deployment-id","_toUniqueId": "catalogue-pod-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "catalogue-pod-id","_toUniqueId": "catalogue-svc-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "catalogue-deployment-id","_toUniqueId": "catalogue-db-id"}'

curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "runsOn","_fromUniqueId": "catalogue-db-id","_toUniqueId": "mongodb-id"}'


# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# CITIES
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","availableReplicas": 1,"createdReplicas": 1,"dataCenter": "demo","desiredReplicas": 1,"entityTypes": ["deployment"],"matchTokens": ["cities"],"name": "cities","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "cities-deployment-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","dataCenter": "demo","entityTypes": ["pod"],"matchTokens": ["cities-pod"],"name": "cities-pod","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "cities-pod-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","dataCenter": "demo","entityTypes": ["service"],"matchTokens": ["cities-svc"],"name": "cities-svc","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "cities-svc-id"}'




curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "cities-deployment-id","_toUniqueId": "cities-pod-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "cities-pod-id","_toUniqueId": "cities-svc-id"}'


# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# MONGODB
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","availableReplicas": 1,"createdReplicas": 1,"dataCenter": "demo","desiredReplicas": 1,"entityTypes": ["volume"],"matchTokens": ["mongodb"],"name": "mongodb","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "mongodb-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","dataCenter": "demo","entityTypes": ["pod"],"matchTokens": ["mongodb-pod"],"name": "mongodb-pod","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "mongodb-pod-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","dataCenter": "demo","entityTypes": ["service"],"matchTokens": ["mongodb-svc"],"name": "mongodb-svc","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "mongodb-svc-id"}'




curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "mongodb-id","_toUniqueId": "mongodb-pod-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "mongodb-pod-id","_toUniqueId": "mongodb-svc-id"}'


# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# REDIS
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","availableReplicas": 1,"createdReplicas": 1,"dataCenter": "demo","desiredReplicas": 1,"entityTypes": ["deployment"],"matchTokens": ["redis-deployment"],"name": "redis-deployment","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "redis-deployment-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","dataCenter": "demo","entityTypes": ["pod"],"matchTokens": ["redis-pod"],"name": "redis-pod","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "redis-pod-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","dataCenter": "demo","entityTypes": ["service"],"matchTokens": ["redis-svc"],"name": "redis-svc","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "redis-svc-id"}'




curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "redis-deployment-id","_toUniqueId": "redis-pod-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "redis-pod-id","_toUniqueId": "redis-svc-id"}'


# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# PAYMENT
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","availableReplicas": 1,"createdReplicas": 1,"dataCenter": "demo","desiredReplicas": 1,"entityTypes": ["deployment"],"matchTokens": ["payment"],"name": "payment","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "payment-deployment-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","dataCenter": "demo","entityTypes": ["pod"],"matchTokens": ["payment-pod"],"name": "payment-pod","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "payment-pod-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","dataCenter": "demo","entityTypes": ["service"],"matchTokens": ["payment-svc"],"name": "payment-svc","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "payment-svc-id"}'



curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "payment-deployment-id","_toUniqueId": "payment-pod-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "payment-pod-id","_toUniqueId": "payment-svc-id"}'



# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# PAYPAL
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","availableReplicas": 1,"createdReplicas": 1,"dataCenter": "demo","desiredReplicas": 1,"entityTypes": ["server"],"matchTokens": ["paypal"],"name": "paypal.com","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "paypal.com-id"}'



curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/resources" --insecure -H 'Content-Type: application/json' -u $NOI_REST_USR':'$NOI_REST_PWD -H 'JobId: listenJob' -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -d $'{"app": "robotshop","availableReplicas": 1,"createdReplicas": 1,"dataCenter": "demo","desiredReplicas": 1,"entityTypes": ["server"],"matchTokens": ["paypal"],"name": "www.paypal.com","namespace": "robot-shop","readyReplicas": 1,"tags": ["app:robotshop","namespace:robot-shop"],"vertexType": "resource","uniqueId": "www.paypal.com-id"}'






# Links Deploy
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "web-deployment-id","_toUniqueId": "shipping-deployment-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "web-deployment-id","_toUniqueId": "catalogue-deployment-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "shipping-deployment-id","_toUniqueId": "cities-deployment-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "shipping-deployment-id","_toUniqueId": "cart-deployment-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "cart-deployment-id","_toUniqueId": "catalogue-deployment-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "cart-deployment-id","_toUniqueId": "redis-deployment-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "cart-deployment-id","_toUniqueId": "payment-deployment-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "payment-deployment-id","_toUniqueId": "user-deployment-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "user-deployment-id","_toUniqueId": "redis-deployment-id"}'


# Links to payment
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "payment-deployment-id","_toUniqueId": "www.paypal.com-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "payment-deployment-id","_toUniqueId": "paypal.com-id"}'


# Links to DB
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "user-deployment-id","_toUniqueId": "user-db-id"}'
curl -X "POST" "https://demo-noi-topology.noi.$CLUSTER_NAME/1.0/rest-observer/rest/references" --insecure -H 'X-TenantID: cfd95b7e-3bc7-4006-a4a8-a73a79c71255' -H 'JobId: listenJob' -H 'Content-Type: application/json; charset=utf-8' -u $NOI_REST_USR':'$NOI_REST_PWD -d $'{"_edgeType": "dependsOn","_fromUniqueId": "catalogue-deployment-id","_toUniqueId": "catalogue-db-id"}'


